[workspace]
members = [
    "qini",
    "qjson", "qjson/bench", "qjson/fuzz", "qjson/nopanic",
    "qptr", "qptr/nopanic", "qptr/san",
]
default-members = ["qini", "qjson", "qptr"]

[profile.bench]
debug = true

[profile.nopanic]
inherits = "release"
panic = "abort"
