[package]
name = "qbump-bench"
version = "1.0.0"
edition = "2021"
publish = false

[dependencies]
criterion = "*"
qbump = { path = ".." }

[[bench]]
name = "bench_qbump"
path = "bench_qbump.rs"
harness = false
